/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3psc;

import javax.swing.JOptionPane;

/**
 *
 * @author Adrielle
 */
public class JanelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPagamento
     */
    public JanelaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrCartaoDeb = new javax.swing.JRadioButton();
        jrCartaoCred = new javax.swing.JRadioButton();
        jrDinheiro = new javax.swing.JRadioButton();
        jbVoltarPag = new javax.swing.JButton();
        jbConluirPag = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jbVoltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Marola", 0, 24)); // NOI18N
        jLabel1.setText("PaGaMeNTo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 20, 152, -1));

        jLabel2.setFont(new java.awt.Font("OCR-A BT", 1, 14)); // NOI18N
        jLabel2.setText("Selecione a forma de pagamento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 158, 290, -1));

        buttonGroup1.add(jrCartaoDeb);
        jrCartaoDeb.setText("Cartão de Débito");
        jrCartaoDeb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrCartaoDeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCartaoDebActionPerformed(evt);
            }
        });
        getContentPane().add(jrCartaoDeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 123, -1));

        buttonGroup1.add(jrCartaoCred);
        jrCartaoCred.setText("Cartão de Crédito");
        jrCartaoCred.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrCartaoCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCartaoCredActionPerformed(evt);
            }
        });
        getContentPane().add(jrCartaoCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 137, -1));

        buttonGroup1.add(jrDinheiro);
        jrDinheiro.setText("Dinheiro");
        jrDinheiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(jrDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 98, -1));

        jbVoltarPag.setText("Voltar");
        jbVoltarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarPagActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltarPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jbConluirPag.setText("Concluir");
        jbConluirPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConluirPagActionPerformed(evt);
            }
        });
        getContentPane().add(jbConluirPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("OCR-A BT", 1, 14)); // NOI18N
        jLabel3.setText("Valor da compra:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 60, 160, -1));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 94, 110, -1));

        jLabel4.setFont(new java.awt.Font("OCR-A BT", 1, 14)); // NOI18N
        jLabel4.setText("Total de itens:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 60, 265, -1));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setText("R$");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 71, -1));

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jbVoltarMenu.setText("Voltar ao menu principal");
        jbVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrCartaoCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCartaoCredActionPerformed
        // TODO add your handling code here:
        jrCartaoDeb.setVisible(false);
        jrDinheiro.setVisible(false);
    }//GEN-LAST:event_jrCartaoCredActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jbVoltarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarPagActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        JanelaPedido telaCam = new JanelaPedido();
        telaCam.setVisible(true);
    }//GEN-LAST:event_jbVoltarPagActionPerformed

    private void jbVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
      
        JanelaMenu telaMenu = new JanelaMenu();
        telaMenu.setVisible(true);
        telaMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbVoltarMenuActionPerformed

    private void jbConluirPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConluirPagActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(null,"Compra efetuada com sucesso");
          // falta cair no bd q foi feito
    }//GEN-LAST:event_jbConluirPagActionPerformed

    private void jrCartaoDebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCartaoDebActionPerformed
        // TODO add your handling code here:
        jrCartaoCred.setVisible(false);
        jrDinheiro.setVisible(false);
    }//GEN-LAST:event_jrCartaoDebActionPerformed

    private void jrDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDinheiroActionPerformed
        // TODO add your handling code here:
        jrCartaoCred.setVisible(false);
        jrCartaoDeb.setVisible(false);
    }//GEN-LAST:event_jrDinheiroActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        jrCartaoCred.setVisible(true);
        jrCartaoDeb.setVisible(true);
        jrDinheiro.setVisible(true);
    }//GEN-LAST:event_jbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConluirPag;
    private javax.swing.JButton jbVoltarMenu;
    private javax.swing.JButton jbVoltarPag;
    private javax.swing.JRadioButton jrCartaoCred;
    private javax.swing.JRadioButton jrCartaoDeb;
    private javax.swing.JRadioButton jrDinheiro;
    // End of variables declaration//GEN-END:variables
}
