package a3psc;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Adrielle
 */
public class JanelaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form JanelaProduto
     */
    public JanelaEstoque() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jbCriar = new javax.swing.JButton();
        jbLimpandoBotton = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jlD = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jlEstampa = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jlNom = new javax.swing.JLabel();
        jlProdutinhoEscolher = new javax.swing.JLabel();
        jrqtde = new javax.swing.JRadioButton();
        jrPreco = new javax.swing.JRadioButton();
        jrCor = new javax.swing.JRadioButton();
        jlNovaCor = new javax.swing.JLabel();
        jbConfirmaProx = new javax.swing.JButton();
        jlSetor = new javax.swing.JLabel();
        jlEstampinha = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        txtNomezinhoEst = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtEstampa = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        jlCorzinha = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        txtCorzinha = new javax.swing.JTextField();
        jbConfirmarSet = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNominho = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jrSetorMenu = new javax.swing.JRadioButton();
        jrEstampaMenu = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        txtQnte = new javax.swing.JTextField();
        jlNewQnte = new javax.swing.JLabel();
        jbMenuCriar = new javax.swing.JButton();
        jbEditar1 = new javax.swing.JButton();
        jbLimpandoBotton1 = new javax.swing.JButton();
        jbLimparCriacao = new javax.swing.JButton();
        jbConfirmarSetorzinho = new javax.swing.JButton();
        jbLimparEdit = new javax.swing.JButton();
        jrProdutoMenuzinho = new javax.swing.JRadioButton();
        jlCriarProduto = new javax.swing.JLabel();
        jbMenuVoltEditzinho = new javax.swing.JButton();
        jbVoltandojr = new javax.swing.JButton();
        jbConfirmarEstSet = new javax.swing.JButton();
        jbLimparEstSet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCriar.setText("Criar");
        jbCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, -1));

        jbLimpandoBotton.setText("Limpar");
        jbLimpandoBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpandoBottonActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpandoBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 90, -1));

        jbApagar.setText("Apagar");
        jbApagar.setEnabled(false);
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jbApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, -1));

        jlD.setText("ID:");
        jlD.setEnabled(false);
        getContentPane().add(jlD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 174, 37, -1));

        txtCor.setEnabled(false);
        txtCor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtCorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        getContentPane().add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 70, -1));

        jlEstampa.setText("Estampa/Setor:");
        jlEstampa.setEnabled(false);
        getContentPane().add(jlEstampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtNome1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNome1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 230, -1));

        jlNom.setText("Nome:");
        jlNom.setEnabled(false);
        getContentPane().add(jlNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jlProdutinhoEscolher.setText("Produtos:");
        jlProdutinhoEscolher.setEnabled(false);
        getContentPane().add(jlProdutinhoEscolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        buttonGroup2.add(jrqtde);
        jrqtde.setText("Qtde");
        jrqtde.setEnabled(false);
        jrqtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrqtdeActionPerformed(evt);
            }
        });
        getContentPane().add(jrqtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        buttonGroup2.add(jrPreco);
        jrPreco.setText("Preço");
        jrPreco.setEnabled(false);
        jrPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(jrPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        buttonGroup2.add(jrCor);
        jrCor.setText("Cor");
        jrCor.setEnabled(false);
        jrCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCorActionPerformed(evt);
            }
        });
        getContentPane().add(jrCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jlNovaCor.setText("Nova Cor:");
        jlNovaCor.setEnabled(false);
        getContentPane().add(jlNovaCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 20));

        jbConfirmaProx.setText("Confirmar");
        jbConfirmaProx.setEnabled(false);
        jbConfirmaProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmaProxActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmaProx, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 90, -1));

        jlSetor.setText("Setor:");
        jlSetor.setEnabled(false);
        getContentPane().add(jlSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, -1));

        jlEstampinha.setText("Estampa:");
        jlEstampinha.setEnabled(false);
        getContentPane().add(jlEstampinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        jlPreco.setText("Preço:");
        jlPreco.setEnabled(false);
        getContentPane().add(jlPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 40, -1));

        txtNomezinhoEst.setEnabled(false);
        txtNomezinhoEst.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNomezinhoEstAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNomezinhoEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomezinhoEstActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomezinhoEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 270, -1));

        txtQuantidade.setEnabled(false);
        txtQuantidade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtQuantidadeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 160, -1));

        txtEstampa.setEnabled(false);
        txtEstampa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtEstampaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstampaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 140, -1));

        txtpreco.setEnabled(false);
        txtpreco.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtprecoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 140, -1));

        jlCorzinha.setText("Cor:");
        jlCorzinha.setEnabled(false);
        getContentPane().add(jlCorzinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 40, -1));

        jlQuantidade.setText("qnte:");
        jlQuantidade.setEnabled(false);
        getContentPane().add(jlQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 40, -1));

        txtSetor.setEnabled(false);
        txtSetor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtSetorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 140, -1));

        txtCorzinha.setEnabled(false);
        txtCorzinha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtCorzinhaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtCorzinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorzinhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorzinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 160, -1));

        jbConfirmarSet.setText("Confirmar");
        jbConfirmarSet.setEnabled(false);
        jbConfirmarSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarSetActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmarSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 90, -1));

        jLabel12.setText("Filtrar Pesquisa:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        txtNominho.setEnabled(false);
        txtNominho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNominhoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNominho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominhoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNominho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 280, -1));

        jLabel18.setFont(new java.awt.Font("Marola", 0, 24)); // NOI18N
        jLabel18.setText("Área de estoque");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 250, 20));

        buttonGroup1.add(jrSetorMenu);
        jrSetorMenu.setText("Setor");
        jrSetorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSetorMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jrSetorMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 60, -1));

        buttonGroup1.add(jrEstampaMenu);
        jrEstampaMenu.setText("Estampa");
        jrEstampaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEstampaMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jrEstampaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, -1));

        txtValor.setEnabled(false);
        txtValor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtValorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 70, -1));

        jlValor.setText("Novo valor R$:");
        jlValor.setEnabled(false);
        getContentPane().add(jlValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        txtQnte.setEnabled(false);
        txtQnte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtQnteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtQnte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQnteActionPerformed(evt);
            }
        });
        getContentPane().add(txtQnte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 70, 30));

        jlNewQnte.setText("Nova Qnte:");
        jlNewQnte.setEnabled(false);
        getContentPane().add(jlNewQnte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jbMenuCriar.setText("Voltar ao menu principal");
        jbMenuCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenuCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        jbEditar1.setText("Editar");
        jbEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, -1));

        jbLimpandoBotton1.setText("Limpar");
        jbLimpandoBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpandoBotton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpandoBotton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 80, -1));

        jbLimparCriacao.setText("Limpar");
        jbLimparCriacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbLimparCriacao.setEnabled(false);
        jbLimparCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCriacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimparCriacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 90, -1));

        jbConfirmarSetorzinho.setText("Confirmar");
        jbConfirmarSetorzinho.setEnabled(false);
        jbConfirmarSetorzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarSetorzinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmarSetorzinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 90, -1));

        jbLimparEdit.setText("Limpar");
        jbLimparEdit.setEnabled(false);
        jbLimparEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimparEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 90, -1));

        buttonGroup1.add(jrProdutoMenuzinho);
        jrProdutoMenuzinho.setText("Produto");
        jrProdutoMenuzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrProdutoMenuzinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jrProdutoMenuzinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, -1));

        jlCriarProduto.setText("Criar Produto:");
        jlCriarProduto.setEnabled(false);
        getContentPane().add(jlCriarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jbMenuVoltEditzinho.setText("Voltar ao menu");
        jbMenuVoltEditzinho.setEnabled(false);
        jbMenuVoltEditzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuVoltEditzinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenuVoltEditzinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jbVoltandojr.setText("Voltar");
        jbVoltandojr.setEnabled(false);
        jbVoltandojr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltandojrActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltandojr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 90, -1));

        jbConfirmarEstSet.setText("Confirmar");
        jbConfirmarEstSet.setEnabled(false);
        getContentPane().add(jbConfirmarEstSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 90, -1));

        jbLimparEstSet.setText("Limpar");
        jbLimparEstSet.setEnabled(false);
        jbLimparEstSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparEstSetActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimparEstSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 90, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 230, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    private void jbCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarActionPerformed
        // TODO add your handling code here:
        //aqui so ficam habilitados os de estampa  e nome e confirma
        jlEstampa.setEnabled(false);
        jlNom.setEnabled(false);
        jbApagar.setEnabled(true);
        
        jlCriarProduto.setEnabled(true);
        jlSetor.setEnabled(true);
        txtSetor.setEnabled(true);
        jlEstampinha.setEnabled(true);
        txtEstampa.setEnabled(true);
        jlPreco.setEnabled(true);
        txtpreco.setEnabled(true);
        jlCorzinha.setEnabled(true);
        txtCorzinha.setEnabled(true);
        jlQuantidade.setEnabled(true);
        txtQuantidade.setEnabled(true);
        jbMenuCriar.setEnabled(true);
        jbConfirmaProx.setEnabled(true);
        jbLimparCriacao.setEnabled(true);

        jbConfirmarEstSet.setEnabled(false);
        jbLimparEstSet.setEnabled(false);
        
        txtNomezinhoEst.setEnabled(false);
        jlProdutinhoEscolher.setEnabled(false);
        
        //inativa id
        jlD.setEnabled(false);
        txtNominho.setEnabled(false);
        jbConfirmarSet.setEnabled(false);
        jbLimparEdit.setEnabled(false);
        
        // editar inativo
        jrqtde.setEnabled(false); 
        jrPreco.setEnabled(false); 
        jrCor.setEnabled(false); 
        jbMenuVoltEditzinho.setEnabled(false); 
        jbConfirmarSetorzinho.setEnabled(false); 
        jbVoltandojr.setEnabled(false); 
        
    }//GEN-LAST:event_jbCriarActionPerformed

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
        // TODO add your handling code here:
        // somente o id e o confirma || esse vai excluir do db o que fora criado
        jlEstampa.setEnabled(true);
        jlNom.setEnabled(true);
        txtNomezinhoEst.setEnabled(true);
        jbLimparCriacao.setEnabled(true);
        jbCriar.setEnabled(true);
        jbConfirmarEstSet.setEnabled(true);
        jbLimparEstSet.setEnabled(true);
        jbLimparCriacao.setEnabled(false);
        jbMenuCriar.setEnabled(true);
        
        // editar inativo
        jrqtde.setEnabled(false); 
        jrPreco.setEnabled(false); 
        jrCor.setEnabled(false); 
        
        jbMenuVoltEditzinho.setEnabled(false); 
        jbConfirmarSetorzinho.setEnabled(false); 
        jbVoltandojr.setEnabled(false); 
        
        // parte do ID
        jlD.setEnabled(true); 
        txtNominho.setEnabled(true); 
        jbConfirmarSet.setEnabled(true); 
        jbLimparEdit.setEnabled(true); 
        
        jlProdutinhoEscolher.setEnabled(false);

        
    }//GEN-LAST:event_jbApagarActionPerformed

    private void txtCorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtCorAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCorAncestorAdded

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtNome1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNome1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1AncestorAdded

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void jrqtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrqtdeActionPerformed
        // TODO add your handling code here:
        // vai mostrar apenas a nova qnt
        jlNewQnte.setEnabled(true);
        txtQnte.setEnabled(true);
        jrPreco.setEnabled(false);
        jrCor.setEnabled(false);
        
        
    }//GEN-LAST:event_jrqtdeActionPerformed

    private void jrPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPrecoActionPerformed
        // TODO add your handling code here:
        //jLabel e txt        
        jlValor.setEnabled(true);
        txtValor.setEnabled(true);
        
        jlNovaCor.setEnabled(false);
        txtCor.setEnabled(false);
        
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
        
        //jRadios
        jrqtde.setEnabled(false);
        jrCor.setEnabled(false);
       
    }//GEN-LAST:event_jrPrecoActionPerformed

    private void jrCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCorActionPerformed
        // TODO add your handling code here:
        jlNovaCor.setEnabled(true);
        txtCor.setEnabled(true);
        
        jlValor.setEnabled(false);
        txtValor.setEnabled(false);
        
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
        
        jrqtde.setEnabled(false);
        jrPreco.setEnabled(false);
               
        
    }//GEN-LAST:event_jrCorActionPerformed

    private void jbConfirmaProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmaProxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmaProxActionPerformed

    private void txtNomezinhoEstAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNomezinhoEstAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomezinhoEstAncestorAdded

    private void txtNomezinhoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomezinhoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomezinhoEstActionPerformed

    private void txtQuantidadeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtQuantidadeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeAncestorAdded

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtEstampaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtEstampaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstampaAncestorAdded

    private void txtEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstampaActionPerformed

    private void txtprecoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtprecoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoAncestorAdded

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoActionPerformed

    private void txtSetorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtSetorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorAncestorAdded

    private void txtSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorActionPerformed

    private void txtCorzinhaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtCorzinhaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorzinhaAncestorAdded

    private void txtCorzinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorzinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorzinhaActionPerformed

    private void jbConfirmarSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmarSetActionPerformed

    private void txtNominhoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNominhoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominhoAncestorAdded

    private void txtNominhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNominhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominhoActionPerformed

    private void jrEstampaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEstampaMenuActionPerformed
        // TODO add your handling code here:
        
        jrSetorMenu.setEnabled(false);
        jrProdutoMenuzinho.setEnabled(false);
    }//GEN-LAST:event_jrEstampaMenuActionPerformed

    private void txtValorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtValorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorAncestorAdded

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtQnteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtQnteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQnteAncestorAdded

    private void txtQnteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQnteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQnteActionPerformed

    private void jbMenuCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuCriarActionPerformed
        // TODO add your handling code here:
         this.dispose();
        
        JanelaMenu telaMenu = new JanelaMenu();
        telaMenu.setVisible(true);
        telaMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbMenuCriarActionPerformed

    private void jrSetorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSetorMenuActionPerformed
        // TODO add your handling code here:
      
        jrEstampaMenu.setEnabled(false);
        jrProdutoMenuzinho.setEnabled(false);
    }//GEN-LAST:event_jrSetorMenuActionPerformed

    private void jbLimpandoBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpandoBottonActionPerformed
        // TODO add your handling code here:
       
        jrProdutoMenuzinho.setEnabled(true);
        jrSetorMenu.setEnabled(true);
        jrEstampaMenu.setEnabled(true);
        
        jbEditar1.setEnabled(true);
        jbConfirmarSet.setEnabled(true);
        jlProdutinhoEscolher.setEnabled(true);
        jrqtde.setEnabled(false);
        jrPreco.setEnabled(false);
        jrCor.setEnabled(false);
        jlValor.setEnabled(false);
        txtValor.setEnabled(false);
        jlNovaCor.setEnabled(false);
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
        jlD.setEnabled(false);
        txtNominho.setEnabled(false);
        jlSetor.setEnabled(false);
        txtSetor.setEnabled(false);
        jlEstampinha.setEnabled(false);
        txtEstampa.setEnabled(false);
        jlPreco.setEnabled(false);
        txtpreco.setEnabled(false);
        jlCorzinha.setEnabled(false);
        txtCorzinha.setEnabled(false);
        jlQuantidade.setEnabled(false);
        txtQuantidade.setEnabled(false);
        jbMenuCriar.setEnabled(true);
        jbConfirmaProx.setEnabled(false);
        jbConfirmarSet.setEnabled(false);
        txtCor.setEnabled(false);
        txtNomezinhoEst.setEnabled(false);
        jlNom.setEnabled(false);
        jlProdutinhoEscolher.setEnabled(false);
        
        jbLimparEdit.setEnabled(false);
        jbConfirmarEstSet.setEnabled(false);
        jbLimparEstSet.setEnabled(false);
        
        jbLimparCriacao.setEnabled(false);
        
        jbMenuVoltEditzinho.setEnabled(false);
        jbConfirmarSetorzinho.setEnabled(false);
        jbVoltandojr.setEnabled(false);
                
    }//GEN-LAST:event_jbLimpandoBottonActionPerformed

    private void jbLimpandoBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpandoBotton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimpandoBotton1ActionPerformed

    private void jbConfirmarSetorzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarSetorzinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmarSetorzinhoActionPerformed

    private void jbLimparEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparEditActionPerformed
        // TODO add your handling code here:
        txtNominho.setText("");
        
    }//GEN-LAST:event_jbLimparEditActionPerformed

    private void jbEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditar1ActionPerformed
        // TODO add your handling code here:
        txtNomezinhoEst.setEnabled(false);
        jbMenuVoltEditzinho.setEnabled(true);
        jbConfirmarSet.setEnabled(false);       
        jlProdutinhoEscolher.setEnabled(true); 
        jrqtde.setEnabled(true); 
        jrPreco.setEnabled(true); 
        jrCor.setEnabled(true); 
        jlValor.setEnabled(false); 
        txtValor.setEnabled(false); 
        jlNovaCor.setEnabled(false); 
        txtCor.setEnabled(false); 
        jlNewQnte.setEnabled(false); 
        txtQnte.setEnabled(false); 
        jbEditar1.setEnabled(true);
        jbApagar.setEnabled(true);
        jbConfirmarSetorzinho.setEnabled(true);
        jbVoltandojr.setEnabled(true);
        
        // parte de criar precisa desativar
        jlCriarProduto.setEnabled(false);
        jlSetor.setEnabled(false);
        txtSetor.setEnabled(false);
        jlEstampinha.setEnabled(false);
        txtEstampa.setEnabled(false);
        jlPreco.setEnabled(false);
        txtpreco.setEnabled(false);
        jlCorzinha.setEnabled(false);
        txtCorzinha.setEnabled(false);
        jlQuantidade.setEnabled(false);
        txtQuantidade.setEnabled(false);
        jbMenuCriar.setEnabled(false);
        jbConfirmaProx.setEnabled(false);
        jbLimparCriacao.setEnabled(false);
        
        //visibilidade do id
        
        jlD.setEnabled(false);
        txtNominho.setEnabled(false);
        jbConfirmarSet.setEnabled(false);
        jbLimparEdit.setEnabled(false);
        
        jbConfirmarEstSet.setEnabled(false);
        jbLimparEstSet.setEnabled(false);
        jlEstampa.setEnabled(false);
        jlNom.setEnabled(false);
    }//GEN-LAST:event_jbEditar1ActionPerformed

    private void jbLimparCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCriacaoActionPerformed
        // TODO add your handling code here:
        txtSetor.setText("");
        txtEstampa.setText("");
        txtpreco.setText("");
        txtCorzinha.setText("");
        txtQuantidade.setText("");
    }//GEN-LAST:event_jbLimparCriacaoActionPerformed

    private void jrProdutoMenuzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrProdutoMenuzinhoActionPerformed
        // TODO add your handling code here:
        jrEstampaMenu.setEnabled(false);
        jrSetorMenu.setEnabled(false);

        
    }//GEN-LAST:event_jrProdutoMenuzinhoActionPerformed

    private void jbMenuVoltEditzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuVoltEditzinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMenuVoltEditzinhoActionPerformed

    private void jbVoltandojrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltandojrActionPerformed
        // TODO add your handling code here:
        
        
        //JRadio
        jrqtde.setEnabled(true);
        jrPreco.setEnabled(true);
        jrCor.setEnabled(true);
        
        // jLabel e txt
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
                
        jlValor.setEnabled(false);
        txtValor.setEnabled(false);
                
        jlNovaCor.setEnabled(false);
        txtCor.setEnabled(false);
                        
        
        txtQnte.setText("");
        txtValor.setText("");
        txtCor.setText("");
    }//GEN-LAST:event_jbVoltandojrActionPerformed

    private void jbLimparEstSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparEstSetActionPerformed
        // TODO add your handling code here:
        txtNomezinhoEst.setText("");
    }//GEN-LAST:event_jbLimparEstSetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbConfirmaProx;
    private javax.swing.JButton jbConfirmarEstSet;
    private javax.swing.JButton jbConfirmarSet;
    private javax.swing.JButton jbConfirmarSetorzinho;
    private javax.swing.JButton jbCriar;
    private javax.swing.JButton jbEditar1;
    private javax.swing.JButton jbLimpandoBotton;
    private javax.swing.JButton jbLimpandoBotton1;
    private javax.swing.JButton jbLimparCriacao;
    private javax.swing.JButton jbLimparEdit;
    private javax.swing.JButton jbLimparEstSet;
    private javax.swing.JButton jbMenuCriar;
    private javax.swing.JButton jbMenuVoltEditzinho;
    private javax.swing.JButton jbVoltandojr;
    private javax.swing.JLabel jlCorzinha;
    private javax.swing.JLabel jlCriarProduto;
    private javax.swing.JLabel jlD;
    private javax.swing.JLabel jlEstampa;
    private javax.swing.JLabel jlEstampinha;
    private javax.swing.JLabel jlNewQnte;
    private javax.swing.JLabel jlNom;
    private javax.swing.JLabel jlNovaCor;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlProdutinhoEscolher;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlValor;
    private javax.swing.JRadioButton jrCor;
    private javax.swing.JRadioButton jrEstampaMenu;
    private javax.swing.JRadioButton jrPreco;
    private javax.swing.JRadioButton jrProdutoMenuzinho;
    private javax.swing.JRadioButton jrSetorMenu;
    private javax.swing.JRadioButton jrqtde;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtCorzinha;
    private javax.swing.JTextField txtEstampa;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNomezinhoEst;
    private javax.swing.JTextField txtNominho;
    private javax.swing.JTextField txtQnte;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSetor;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
