/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3psc;

/**
 *
 * @author Adrielle
 */
public class JanelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMenu
     */
    public JanelaMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmMenuPedido = new javax.swing.JMenu();
        jmMenuPagamento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jMenu1.setText("Estoque");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jmMenuPedido.setMnemonic('S');
        jmMenuPedido.setText("Pedido");
        jmMenuPedido.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmMenuPedidoMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        jmMenuPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuPedidoMouseClicked(evt);
            }
        });
        jmMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuPedidoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmMenuPedido);

        jmMenuPagamento.setMnemonic('D');
        jmMenuPagamento.setText("Pagamento");
        jmMenuPagamento.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmMenuPagamentoMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmMenuPagamentoMenuSelected(evt);
            }
        });
        jmMenuPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuPagamentoMouseClicked(evt);
            }
        });
        jmMenuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuPagamentoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmMenuPagamento);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuPedidoMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmMenuPedidoMenuDeselected
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jmMenuPedidoMenuDeselected

    private void jmMenuPagamentoMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmMenuPagamentoMenuDeselected
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jmMenuPagamentoMenuDeselected

    private void jmMenuPagamentoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmMenuPagamentoMenuSelected
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmMenuPagamentoMenuSelected

    private void jmMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuPedidoActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jmMenuPedidoActionPerformed

    private void jmMenuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuPagamentoActionPerformed
    
    }//GEN-LAST:event_jmMenuPagamentoActionPerformed

    private void jmMenuPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuPagamentoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        JanelaPagamento tela = new JanelaPagamento();
        tela.setVisible(true);
        
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmMenuPagamentoMouseClicked

    private void jmMenuPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuPedidoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        JanelaPedido telinha = new JanelaPedido();
        telinha.setVisible(true);
        telinha.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmMenuPedidoMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        this.dispose();
         JanelaEstoque telona = new JanelaEstoque();
        telona.setVisible(true);
        telona.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmMenuPagamento;
    private javax.swing.JMenu jmMenuPedido;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
