/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3psc;

/**
 *
 * @author Adrielle
 */
public class JanelaEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaEditarUsuario
     */
    public JanelaEditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnApagar = new javax.swing.JButton();
        jNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jbSalvarEditar = new javax.swing.JButton();
        jrNome = new javax.swing.JRadioButton();
        jrSenha = new javax.swing.JRadioButton();
        jrAmbos = new javax.swing.JRadioButton();
        jbMenuCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Marola", 0, 24)); // NOI18N
        jLabel1.setText("editando usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel2.setText("Usuários cadastrados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 270));

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jNome.setText("Nome:");
        jNome.setEnabled(false);
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 250, -1));

        jSenha.setText("Senha:");
        jSenha.setEnabled(false);
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtSenha.setEnabled(false);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 250, -1));

        jbSalvarEditar.setText("Salvar");
        jbSalvarEditar.setEnabled(false);
        getContentPane().add(jbSalvarEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 80, -1));

        jrNome.setText("Nome");
        jrNome.setEnabled(false);
        getContentPane().add(jrNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jrSenha.setText("Senha");
        jrSenha.setEnabled(false);
        getContentPane().add(jrSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jrAmbos.setText("Ambos");
        jrAmbos.setEnabled(false);
        getContentPane().add(jrAmbos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jbMenuCriar.setText("Voltar ao menu principal");
        jbMenuCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenuCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jbMenuCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuCriarActionPerformed
        // TODO add your handling code here:
        this.dispose();

        JanelaMenu telaMenu = new JanelaMenu();
        telaMenu.setVisible(true);
        telaMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbMenuCriarActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        
        // botoes
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        
        // campos habilitados
       
        jNome.setEnabled(true);
        txtNome.setEnabled(true);
        jSenha.setEnabled(true);
        txtSenha.setEnabled(true);
        jbSalvarEditar.setEnabled(true);
        
        // campos desabilitados
        jrNome.setEnabled(false);
        jrSenha.setEnabled(false);
        jrAmbos.setEnabled(false);

        
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        jrNome.setEnabled(true);
        jrSenha.setEnabled(true);
        jrAmbos.setEnabled(true);
       
        jrNome.setEnabled(true);
        jrSenha.setEnabled(true);
        jrAmbos.setEnabled(true);
        jNome.setEnabled(true);
        txtNome.setEnabled(true);
        jSenha.setEnabled(true);
        txtSenha.setEnabled(true);
        jbSalvarEditar.setEnabled(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        //botoes
        btnCriar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        // campos
        jrNome.setEnabled(false);
        jrSenha.setEnabled(false);
        jrAmbos.setEnabled(false);
        jNome.setEnabled(false);
        txtNome.setEnabled(false);
        jSenha.setEnabled(false);
        txtSenha.setEnabled(false);
        jbSalvarEditar.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        
        btnEditar.setEnabled(false);
        btnCriar.setEnabled(false);
         
        jNome.setEnabled(true);
        txtNome.setEnabled(true);
        jSenha.setEnabled(true);
        txtSenha.setEnabled(true);
        jbSalvarEditar.setEnabled(true);
        
        jrNome.setEnabled(false);
        jrSenha.setEnabled(false);
        jrAmbos.setEnabled(false);
    }//GEN-LAST:event_btnApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSenha;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbMenuCriar;
    private javax.swing.JButton jbSalvarEditar;
    private javax.swing.JRadioButton jrAmbos;
    private javax.swing.JRadioButton jrNome;
    private javax.swing.JRadioButton jrSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtNome3;
    private javax.swing.JTextField txtNome4;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
