
package a3psc;

public class JanelaEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaEditarUsuario
     */
    public JanelaEditarUsuario() {
        initComponents();
    }

    private char cea; 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea1.setText(Login.listarUsuarios());
        btnApagar = new javax.swing.JButton();
        jNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jbSalvarEditar = new javax.swing.JButton();
        jrNome = new javax.swing.JRadioButton();
        jrSenha = new javax.swing.JRadioButton();
        jbMenuCriar = new javax.swing.JButton();
        jlErro = new javax.swing.JLabel();
        jlErro.setVisible(false);
        jlOK = new javax.swing.JLabel();
        jlOK.setVisible(false);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setEnabled(false);
        jNovoNome = new javax.swing.JLabel();
        jNovoNome.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(654, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Marola", 3, 24)); // NOI18N
        jLabel1.setText("Gerenciar Usuários");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 230, -1));

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel2.setText("Usuários cadastrados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 20));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 160, 270));

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jNome.setText("Nome:");
        jNome.setEnabled(false);
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 250, -1));

        jSenha.setText("Senha:");
        jSenha.setEnabled(false);
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 50, 20));

        txtSenha.setEnabled(false);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 250, -1));

        jbSalvarEditar.setText("Salvar");
        jbSalvarEditar.setEnabled(false);
        jbSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalvarEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 80, -1));

        jrNome.setText("Nome");
        jrNome.setEnabled(false);
        jrNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jrNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jrSenha.setText("Senha");
        jrSenha.setEnabled(false);
        jrSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jrSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jbMenuCriar.setText("Voltar ao menu principal");
        jbMenuCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenuCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, -1));

        jlErro.setForeground(new java.awt.Color(255, 102, 102));
        jlErro.setText("[mensagens de erro aq]");
        getContentPane().add(jlErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 210, 20));

        jlOK.setForeground(new java.awt.Color(0, 204, 0));
        jlOK.setText("[mensagens OK]");
        getContentPane().add(jlOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 306, 170, 20));

        jLabel3.setText("O que editar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, 20));

        jNovoNome.setText("Novo Nome:");
        getContentPane().add(jNovoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ativNome(boolean tf){
        jNome.setEnabled(tf);
        txtNome.setEnabled(tf);
    }
    
    private void ativSenha(boolean tf){
        jSenha.setEnabled(tf);
        txtSenha.setEnabled(tf);
    }
    
    private void ativJr(boolean tf){
        jrNome.setEnabled(tf);
        jrSenha.setEnabled(tf);
    }
    
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    
    private void criarUsuario(){
        String usuario = txtNome.getText();
        String senha = txtSenha.getText();
        if(!Login.checarUsuario(usuario)){
            if(Login.usuarioOK(usuario)){
                Login.cadastrar(usuario, senha);
                jlOK.setText("Usuário cadastrado");
                jlOK.setVisible(true);
                limpar();
            }
            else{
                jlErro.setText("Nome de usuário muito curto.");
                jlErro.setVisible(true);
            }
        }
        else{
            jlErro.setText("Nome de usuário já em uso");
            jlErro.setVisible(true);
        }
    }
    
    private void editarNome(){
        String usuario = txtNome.getText();
        String novoUsuario = txtSenha.getText();
        if(Login.checarUsuario(usuario)){
            if(Login.usuarioOK(usuario)){
                Login.editarUsuario(usuario, novoUsuario);
                jlOK.setText("Nome de usuário alterado.");
                jlOK.setVisible(true);
                limpar();
            }
            else{
                jlErro.setText("Nome de usuário muito curto.");
                jlErro.setVisible(true);
            }
        }
        else{
            jlErro.setText("Usuário inexistente.");
            jlErro.setVisible(true);
        }
    }
    
    private void editarSenha(){
        String usuario = txtNome.getText();
        String senha = txtSenha.getText();
        if(Login.checarUsuario(usuario)){
            Login.editarSenha(usuario, senha);
            jlOK.setText("Senha alterada.");
            jlOK.setVisible(true);
            limpar();
        }
        else{
            jlErro.setText("Usuário inexistente.");
            jlErro.setVisible(true);
        }
    
    }
    
    private void apagarUsuario(){
        String usuario = txtNome.getText();
        if(Login.checarUsuario(usuario)){
            Login.deletarUsuario(usuario);
            jlOK.setText("Usuário removido.");
            jlOK.setVisible(true);
            limpar();
        }
        else{
            jlErro.setText("Usuário inexistente.");
            jlErro.setVisible(true);
        }
    }
    
    private void limpar(){
        jlErro.setVisible(false);
        //botoes
        btnCriar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        // campos
        jrNome.setEnabled(false);
        jSenha.setVisible(true);
        jrSenha.setEnabled(false);
        jNome.setEnabled(false);
        txtNome.setEnabled(false);
        jSenha.setEnabled(false);
        txtSenha.setEnabled(false);
        jbSalvarEditar.setEnabled(false);
        jNovoNome.setVisible(false);
        txtNome.setText("");
        txtSenha.setText("");
        
        jrSenha.setSelected(false);
        jrNome.setSelected(false);
        jTextArea1.setText(Login.listarUsuarios());
    }
    
    
    
    
    
    
    
    
    
    private void jbMenuCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuCriarActionPerformed
        // TODO add your handling code here:
        this.dispose();

        JanelaMenu telaMenu = new JanelaMenu();
        telaMenu.setVisible(true);
        telaMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbMenuCriarActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        jlOK.setVisible(false);
        jlErro.setVisible(false);
        cea = 'C';
        // botoes
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        
        // campos habilitados
       
        ativNome(true);
        ativSenha(true);
        jbSalvarEditar.setEnabled(true);
        
        // campos desabilitados
        ativJr(false);

        
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        jlOK.setVisible(false);
        jlErro.setVisible(false);
        cea = 'E';
        jLabel3.setEnabled(true);
        ativJr(true);
        ativNome(false);
        ativSenha(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        jlOK.setVisible(false);
        jlErro.setVisible(false);
        cea = 'A';
        btnEditar.setEnabled(false);
        btnCriar.setEnabled(false);
        jbSalvarEditar.setEnabled(true);
        ativNome(true);
        ativSenha(false);
        ativJr(false);
    }//GEN-LAST:event_btnApagarActionPerformed

    private void jrNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNomeActionPerformed
         jlOK.setVisible(false);
         jlErro.setVisible(false);
         jbSalvarEditar.setEnabled(true);
        if(jrNome.isSelected()){
            ativNome(true);
            ativSenha(true);
            jrSenha.setSelected(false);
            jNovoNome.setVisible(true);
            jSenha.setVisible(false);
        }
    }//GEN-LAST:event_jrNomeActionPerformed

    private void jrSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSenhaActionPerformed
        jlOK.setVisible(false);
        jlErro.setVisible(false);
        jbSalvarEditar.setEnabled(true);
        if(jrSenha.isSelected()){
            ativNome(true);
            ativSenha(true);
            jrNome.setSelected(false);
            jNovoNome.setVisible(false);
            jSenha.setVisible(true);
        }
    }//GEN-LAST:event_jrSenhaActionPerformed

    private void jbSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarEditarActionPerformed
        if (cea == 'C'){        // criar
            criarUsuario();
        }
        else if(cea == 'E' && jrNome.isSelected()){
            editarNome();
        }
        else if(cea == 'E' && jrSenha.isSelected()){
            editarSenha();
        }
        else if(cea == 'A'){
            apagarUsuario();
        }
        
    }//GEN-LAST:event_jbSalvarEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNovoNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSenha;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbMenuCriar;
    private javax.swing.JButton jbSalvarEditar;
    private javax.swing.JLabel jlErro;
    private javax.swing.JLabel jlOK;
    private javax.swing.JRadioButton jrNome;
    private javax.swing.JRadioButton jrSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
