package a3psc;

public class JanelaEstoque extends javax.swing.JFrame {

    private char pes;       // produto, estampa, setor
    private char cea;       // criar, editar, apagar
    private char prodQPC;   // editar produto: quantidade, preço, cor 
    private ProdutoDAO ProdutoDAO = new ProdutoDAO();
    /**
     * Creates new form JanelaProduto
     */
    public JanelaEstoque() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jbCriar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jlD = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jlNomeSetor = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jlNomeEstampa = new javax.swing.JLabel();
        jlProdutinhoEscolher = new javax.swing.JLabel();
        jrqtde = new javax.swing.JRadioButton();
        jrPreco = new javax.swing.JRadioButton();
        jrCor = new javax.swing.JRadioButton();
        jlNovaCor = new javax.swing.JLabel();
        jbConfirmaProx = new javax.swing.JButton();
        jlSetor = new javax.swing.JLabel();
        jlEstampinha = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        txtNomeEstampa = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtEstampa = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        jlCorzinha = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        txtCorzinha = new javax.swing.JTextField();
        jbConfirmarSet = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNominho = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jrSetorMenu = new javax.swing.JRadioButton();
        jrEstampaMenu = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        txtQnte = new javax.swing.JTextField();
        jlNewQnte = new javax.swing.JLabel();
        jbMenuCriar = new javax.swing.JButton();
        jbEditar1 = new javax.swing.JButton();
        jbLimpandoBotton1 = new javax.swing.JButton();
        jbLimparCriacao = new javax.swing.JButton();
        jbConfirmarSetorzinho = new javax.swing.JButton();
        jbLimparEdit = new javax.swing.JButton();
        jrProdutoMenuzinho = new javax.swing.JRadioButton();
        jlCriarProduto = new javax.swing.JLabel();
        jbMenuVoltEditzinho = new javax.swing.JButton();
        jbVoltandojr = new javax.swing.JButton();
        jbConfirmarEstSet = new javax.swing.JButton();
        jbLimparEstSet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsulta = new javax.swing.JTextPane();
        jbPesquisar = new javax.swing.JButton();
        jlErroSelecionar = new javax.swing.JLabel();
        jlErroIdInvalido = new javax.swing.JLabel();
        jlErroIdInvalido.setVisible(false);
        jlErroESExiste = new javax.swing.JLabel();
        jlErroESExiste.setVisible(false);
        jlErroValorInvalido = new javax.swing.JLabel();
        jlErroValorInvalido.setVisible(false);
        jlErroCriarProd = new javax.swing.JLabel();
        jlErroCriarProd.setVisible(false);
        jlConcluido = new javax.swing.JLabel();
        jlConcluido.setVisible(false);
        txtNomeSetor = new javax.swing.JTextField();
        jlSetorEstampa = new javax.swing.JLabel();
        jlSetorEstampa.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCriar.setText("Criar");
        jbCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, -1));

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 90, -1));

        jbApagar.setText("Apagar");
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jbApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, -1));

        jlD.setText("ID:");
        jlD.setEnabled(false);
        getContentPane().add(jlD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 174, 37, -1));

        txtCor.setEnabled(false);
        txtCor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtCorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        getContentPane().add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 70, -1));

        jlNomeSetor.setText("Setor:");
        jlNomeSetor.setEnabled(false);
        getContentPane().add(jlNomeSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        txtNome1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNome1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 170, -1));

        jlNomeEstampa.setText("Estampa:");
        jlNomeEstampa.setEnabled(false);
        getContentPane().add(jlNomeEstampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jlProdutinhoEscolher.setText("Produtos:");
        jlProdutinhoEscolher.setEnabled(false);
        getContentPane().add(jlProdutinhoEscolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        buttonGroup2.add(jrqtde);
        jrqtde.setText("Qtde");
        jrqtde.setEnabled(false);
        jrqtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrqtdeActionPerformed(evt);
            }
        });
        getContentPane().add(jrqtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        buttonGroup2.add(jrPreco);
        jrPreco.setText("Preço");
        jrPreco.setEnabled(false);
        jrPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(jrPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        buttonGroup2.add(jrCor);
        jrCor.setText("Cor");
        jrCor.setEnabled(false);
        jrCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCorActionPerformed(evt);
            }
        });
        getContentPane().add(jrCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jlNovaCor.setText("Nova Cor:");
        jlNovaCor.setEnabled(false);
        getContentPane().add(jlNovaCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 20));

        jbConfirmaProx.setText("Confirmar");
        jbConfirmaProx.setEnabled(false);
        jbConfirmaProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmaProxActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmaProx, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 90, -1));

        jlSetor.setText("Setor:");
        jlSetor.setEnabled(false);
        getContentPane().add(jlSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, -1));

        jlEstampinha.setText("Estampa:");
        jlEstampinha.setEnabled(false);
        getContentPane().add(jlEstampinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        jlPreco.setText("Preço:");
        jlPreco.setEnabled(false);
        getContentPane().add(jlPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 40, -1));

        txtNomeEstampa.setEnabled(false);
        txtNomeEstampa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNomeEstampaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNomeEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEstampaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeEstampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 270, -1));

        txtQuantidade.setEnabled(false);
        txtQuantidade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtQuantidadeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 160, -1));

        txtEstampa.setEnabled(false);
        txtEstampa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtEstampaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstampaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 140, -1));

        txtpreco.setEnabled(false);
        txtpreco.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtprecoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 140, -1));

        jlCorzinha.setText("Cor:");
        jlCorzinha.setEnabled(false);
        getContentPane().add(jlCorzinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 40, -1));

        jlQuantidade.setText("qnte:");
        jlQuantidade.setEnabled(false);
        getContentPane().add(jlQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 40, -1));

        txtSetor.setEnabled(false);
        txtSetor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtSetorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 140, -1));

        txtCorzinha.setEnabled(false);
        txtCorzinha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtCorzinhaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtCorzinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorzinhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorzinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 160, -1));

        jbConfirmarSet.setText("Confirmar");
        jbConfirmarSet.setEnabled(false);
        jbConfirmarSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarSetActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmarSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 90, -1));

        jLabel12.setText("Filtrar Pesquisa:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        txtNominho.setEnabled(false);
        txtNominho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNominhoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNominho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominhoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNominho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 280, -1));

        jLabel18.setFont(new java.awt.Font("Marola", 0, 24)); // NOI18N
        jLabel18.setText("Área de estoque");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 250, 20));

        buttonGroup1.add(jrSetorMenu);
        jrSetorMenu.setText("Setor");
        jrSetorMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrSetorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSetorMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jrSetorMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 60, -1));

        buttonGroup1.add(jrEstampaMenu);
        jrEstampaMenu.setText("Estampa");
        jrEstampaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEstampaMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jrEstampaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, -1));

        txtValor.setEnabled(false);
        txtValor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtValorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 70, -1));

        jlValor.setText("Novo valor R$:");
        jlValor.setEnabled(false);
        getContentPane().add(jlValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        txtQnte.setEnabled(false);
        txtQnte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtQnteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtQnte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQnteActionPerformed(evt);
            }
        });
        getContentPane().add(txtQnte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 70, 30));

        jlNewQnte.setText("Nova Qnte:");
        jlNewQnte.setEnabled(false);
        getContentPane().add(jlNewQnte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jbMenuCriar.setText("Voltar ao menu principal");
        jbMenuCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenuCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        jbEditar1.setText("Editar");
        jbEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, -1));

        jbLimpandoBotton1.setText("Limpar");
        jbLimpandoBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpandoBotton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpandoBotton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 80, -1));

        jbLimparCriacao.setText("Limpar");
        jbLimparCriacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbLimparCriacao.setEnabled(false);
        jbLimparCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCriacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimparCriacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 90, -1));

        jbConfirmarSetorzinho.setText("Confirmar");
        jbConfirmarSetorzinho.setEnabled(false);
        jbConfirmarSetorzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarSetorzinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmarSetorzinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 90, -1));

        jbLimparEdit.setText("Limpar");
        jbLimparEdit.setEnabled(false);
        jbLimparEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimparEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 90, -1));

        buttonGroup1.add(jrProdutoMenuzinho);
        jrProdutoMenuzinho.setText("Produto");
        jrProdutoMenuzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrProdutoMenuzinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jrProdutoMenuzinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, -1));

        jlCriarProduto.setText("Criar Produto:");
        jlCriarProduto.setEnabled(false);
        getContentPane().add(jlCriarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jbMenuVoltEditzinho.setText("Voltar ao menu");
        jbMenuVoltEditzinho.setEnabled(false);
        jbMenuVoltEditzinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuVoltEditzinhoActionPerformed(evt);
            }
        });
        getContentPane().add(jbMenuVoltEditzinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jbVoltandojr.setText("Voltar");
        jbVoltandojr.setEnabled(false);
        jbVoltandojr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltandojrActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltandojr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 90, -1));

        jbConfirmarEstSet.setText("Confirmar");
        jbConfirmarEstSet.setEnabled(false);
        jbConfirmarEstSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarEstSetActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmarEstSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 90, -1));

        jbLimparEstSet.setText("Limpar");
        jbLimparEstSet.setEnabled(false);
        jbLimparEstSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparEstSetActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimparEstSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 90, -1));

        txtConsulta.setEditable(false);
        jScrollPane1.setViewportView(txtConsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 230, 550));

        jbPesquisar.setText("🔎");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 60, 20));

        jlErroSelecionar.setForeground(new java.awt.Color(204, 0, 0));
        jlErroSelecionar.setText("Selecione uma das seguintes opções primeiro:");
        getContentPane().add(jlErroSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 340, 20));
        jlErroSelecionar.setVisible(false);

        jlErroIdInvalido.setForeground(new java.awt.Color(204, 0, 0));
        jlErroIdInvalido.setText("O ID inserido é inválido.");
        getContentPane().add(jlErroIdInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 280, -1));

        jlErroESExiste.setForeground(new java.awt.Color(204, 0, 0));
        jlErroESExiste.setText("Estampa ou Setor já existente.");
        getContentPane().add(jlErroESExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 270, -1));

        jlErroValorInvalido.setForeground(new java.awt.Color(204, 0, 0));
        jlErroValorInvalido.setText("Valor inserido inválido.");
        getContentPane().add(jlErroValorInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jlErroCriarProd.setForeground(new java.awt.Color(204, 0, 0));
        jlErroCriarProd.setText("msg - erro");
        getContentPane().add(jlErroCriarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 200, -1));

        jlConcluido.setForeground(new java.awt.Color(0, 102, 0));
        jlConcluido.setText("Operação concluída!");
        getContentPane().add(jlConcluido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, -1));

        txtNomeSetor.setEnabled(false);
        txtNomeSetor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNomeSetorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtNomeSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeSetorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, -1));

        jlSetorEstampa.setText("Nome Setor/Estampa");
        getContentPane().add(jlSetorEstampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* --------------------------------
    * MÉTODOS - ATIVAR/DESATIVAR CUSTOM
    ----------------------------------- */
    
    private void ativSecao1(boolean tf){
        jlD.setEnabled(tf);
        txtNominho.setEnabled(tf);
        jbConfirmarSet.setEnabled(tf);
        jbLimparEdit.setEnabled(tf); 
    }
    
    private void ativSecao2(boolean tf){
        jlNomeSetor.setEnabled(tf);
        jlNomeEstampa.setEnabled(tf);
        jlSetorEstampa.setEnabled(tf);
        txtNomeEstampa.setEnabled(tf);
        txtNomeSetor.setEnabled(tf);
        jbConfirmarEstSet.setEnabled(tf);
        jbLimparEstSet.setEnabled(tf);
    }
    
    private void ativSecao3(boolean tf){
        jlNewQnte.setEnabled(tf);
        jlValor.setEnabled(tf);
        jlNovaCor.setEnabled(tf);
        txtQnte.setEnabled(tf);
        txtValor.setEnabled(tf);
        txtCor.setEnabled(tf);
        jlProdutinhoEscolher.setEnabled(tf);
        jrqtde.setEnabled(tf);
        jrPreco.setEnabled(tf);
        jrCor.setEnabled(tf);
        jbMenuVoltEditzinho.setEnabled(tf);
        jbConfirmarSetorzinho.setEnabled(tf);
        jbVoltandojr.setEnabled(tf);
    
    }
    
    private void ativSecao4(boolean tf){
        jlCriarProduto.setEnabled(tf);
        jlSetor.setEnabled(tf);
        jlEstampinha.setEnabled(tf);
        jlPreco.setEnabled(tf);
        jlCorzinha.setEnabled(tf);
        jlQuantidade.setEnabled(tf);
        txtSetor.setEnabled(tf);
        txtEstampa.setEnabled(tf);
        txtpreco.setEnabled(tf);
        txtCorzinha.setEnabled(tf);
        txtQuantidade.setEnabled(tf);
        jbConfirmaProx.setEnabled(tf);
        jbLimparCriacao.setEnabled(tf);
    }
    
    /* --------------------------------
    * MÉTODOS - AÇÕES
    ----------------------------------- */
    
    // MÉTODO: limpar/dar reset na página
    private void limpar(){
       
        // desativando seções de operações
        ativSecao1(false);
        ativSecao2(false);
        ativSecao3(false);
        ativSecao4(false);
        
        // ativando todos os menus
        jrProdutoMenuzinho.setEnabled(true);
        jrSetorMenu.setEnabled(true);
        jrEstampaMenu.setEnabled(true);
        
        // ativando os botões
        jbCriar.setEnabled(true);
        jbEditar1.setEnabled(true);
        jbApagar.setEnabled(true);
        jbLimpar.setEnabled(true);
        
        // limpando msgs de erro
        jlErroSelecionar.setVisible(false);
        jlErroIdInvalido.setVisible(false);
        jlErroESExiste.setVisible(false);
        jlErroValorInvalido.setVisible(false);
        jlErroCriarProd.setVisible(false);
        
        // resetando msg de erro q muda
        jlErroIdInvalido.setText("O ID inserido é inválido.");
        
        // limpando as caixas de texto
        txtNominho.setText("");
        txtNomeSetor.setText("");
        txtNomeEstampa.setText("");
        txtQnte.setText("");
        txtValor.setText("");
        txtCor.setText("");
        txtSetor.setText("");
        txtEstampa.setText("");
        txtpreco.setText("");
        txtCorzinha.setText("");
        txtQuantidade.setText("");
    }
    
    /*~MÉTODOS: AÇÕES CRUD~*/
    // CRIAR SETOR
    private void criarSetor(){
        String nomeSetor = txtNomeSetor.getText();
        if(!ProdutoDAO.checarSetor(nomeSetor)){
            ProdutoDAO.criarSetor(nomeSetor);
            jlErroESExiste.setVisible(false);
            jlConcluido.setVisible(true);
            limpar();
        }
        else{
            jlErroESExiste.setVisible(true);
        }
    }
    
    // MÉTODO: criar nova estampa
    private void criarEstampa(){
        String nomeEstampa = txtNomeEstampa.getText();
        String nomeSetor = txtNomeSetor.getText();
        
        if(!ProdutoDAO.checarEstampa(nomeSetor,nomeEstampa)){
            ProdutoDAO.criarEstampa(nomeSetor, nomeEstampa);
            jlErroESExiste.setVisible(true);
            jlConcluido.setVisible(true);
            limpar();
        }
        else{
            jlErroESExiste.setVisible(true);
        }
    
    }
    
    // MÉTODO: criar produto novo
    private void criarProduto(){
        // pegando valores
        String setor = txtSetor.getText();
        String estampa = txtEstampa.getText();
        String cor = txtCorzinha.getText();
        int qtde = 0;
        double preco = 0;
        
        //setando qtde
        if(txtQuantidade.getText().isEmpty()){
            qtde = 0;
        }
        else{
            qtde = Integer.parseInt(txtQuantidade.getText());
        }
        // setando preço
        if(txtpreco.getText().isEmpty()){
            preco = Produto.precoBase;
        }
        else{
            preco = Double.parseDouble(txtpreco.getText());
        }
        
        // testar setor, testar estampa, ver se já existe o produto
        
        if(!ProdutoDAO.checarSetor(setor)){                                     // se o setor nn existir
            jlErroCriarProd.setText("Setor inexistente");
            jlErroCriarProd.setVisible(true);
        }
        else{
            if(!ProdutoDAO.checarEstampa(setor, estampa)){                      // se a estampa nn existir
            jlErroCriarProd.setText("Estampa inexistente");
            jlErroCriarProd.setVisible(true);
            }
            else{
                int idEstampa = ProdutoDAO.getIdEstampa(setor, estampa);
                if(ProdutoDAO.checarProduto(setor, idEstampa, cor)){            // se o produto existir
                    jlErroCriarProd.setText("Produto já existe");
                    jlErroCriarProd.setVisible(true);
                }
                else{
                    ProdutoDAO.criarProduto(setor, cor, estampa, qtde, preco);
                    jlConcluido.setVisible(true);
                    limpar();
                }
            
            
            }
            
        }
        
        
    }

    // MÉTODO: mudar nome de um setor
    private void editarSetor(){
        String setor = txtNominho.getText();
        String novoSetor = txtNomeSetor.getText();
        
        if (ProdutoDAO.checarSetor(setor)){                                     // ver se o setor existe
            ProdutoDAO.editarSetor(setor,novoSetor);
            jlConcluido.setVisible(true);
            limpar();
        } else {
            jlErroIdInvalido.setText("Nome de setor inválido.");
            jlErroIdInvalido.setVisible(true);
        }
    
    }
    
    private void editarEstampa(){
        try {
            int idEstampa = Integer.parseInt(txtNominho.getText());
            String novaEstampa = txtNomeEstampa.getText();
        
            if(ProdutoDAO.checarEstampa(idEstampa)){                                // ver se a estampa existe
                ProdutoDAO.editarEstampa(idEstampa, novaEstampa);
                jlConcluido.setVisible(true);
                limpar();
            } else{
                jlErroIdInvalido.setText("O ID inserido é inválido.");
                jlErroIdInvalido.setVisible(true);
            }
        } catch (NumberFormatException nfe){
            jlErroIdInvalido.setText("O ID deve ser um número inteiro");
            jlErroIdInvalido.setVisible(true);
        }
        
    
    }
    
    // MÉTODO: editar preço de um produto
    private void editarProdPreco(){
        try{
            int idProd = Integer.parseInt(txtNominho.getText());
            double novoPreco = Double.parseDouble(txtValor.getText());
            
            if(ProdutoDAO.checarProduto(idProd)){
                ProdutoDAO.editarPreco(idProd,novoPreco);
                jlConcluido.setVisible(true);
                limpar();
            } else{
                jlErroIdInvalido.setText("O ID inserido é inválido.");
                jlErroIdInvalido.setVisible(true);
            }
        }catch(NumberFormatException nfe){
           jlErroIdInvalido.setText("O ID deve ser um número inteiro");
           jlErroIdInvalido.setVisible(true); 
        }
    }
    
    //MÉTODO: editar quantidade de um produto
    private void editarProdQtde(){
         try{
            int idProd = Integer.parseInt(txtNominho.getText());
            int novaQtde = Integer.parseInt(txtQnte.getText());
            
            if(ProdutoDAO.checarProduto(idProd)){
                ProdutoDAO.editarQtde(idProd,novaQtde);
                jlConcluido.setVisible(true);
                limpar();
            } else{
                jlErroIdInvalido.setText("O ID inserido é inválido.");
                jlErroIdInvalido.setVisible(true);
            }
        }catch(NumberFormatException nfe){
           jlErroIdInvalido.setText("O ID deve ser um número inteiro");
           jlErroIdInvalido.setVisible(true); 
        }
    
    }
    
    // MÉTODO: editar cor de um produto
    private void editarProdCor(){
     try{
        int idProd = Integer.parseInt(txtNominho.getText());
        String novaCor = txtCor.getText();

        if(ProdutoDAO.checarProduto(idProd)){
            ProdutoDAO.editarCor(idProd,novaCor);
            jlConcluido.setVisible(true);
            limpar();
        } else{
            jlErroIdInvalido.setText("O ID inserido é inválido.");
            jlErroIdInvalido.setVisible(true);
        }
        }catch(NumberFormatException nfe){
           jlErroIdInvalido.setText("O ID deve ser um número inteiro");
           jlErroIdInvalido.setVisible(true); 
        }
    }
    
    // MÉTODO: apagar um setor
    private void apagarSetor(){
        String setor = txtNominho.getText();
        if(ProdutoDAO.checarSetor(setor)){
            ProdutoDAO.delSetor(setor);
            jlConcluido.setVisible(true);
            limpar();
        }
        else{
            jlErroIdInvalido.setText("O ID inserido é inválido.");
            jlErroIdInvalido.setVisible(true);
        }
    }
    
    private void apagarEstampa(){
        int idEstampa = Integer.parseInt(txtNominho.getText());
        if(ProdutoDAO.checarEstampa(idEstampa)){
            ProdutoDAO.delEstampa(idEstampa);
            jlConcluido.setVisible(true);
            limpar();
        }
        else{
            jlErroIdInvalido.setText("O ID inserido é inválido.");
            jlErroIdInvalido.setVisible(true);
        }
    }
    
    private void apagarProduto(){
    
        try{
            int idProd = Integer.parseInt(txtNominho.getText());
            if(ProdutoDAO.checarProduto(idProd)){
                ProdutoDAO.delProd(idProd);
                jlConcluido.setVisible(true);
                limpar();
            }
            else{
                jlErroIdInvalido.setText("O ID inserido é inválido.");
                jlErroIdInvalido.setVisible(true);
            }
        }
        catch(NumberFormatException nfe){
            jlErroIdInvalido.setText("O ID deve ser um número inteiro");
           jlErroIdInvalido.setVisible(true); 
        }
    }
    
    
    
    /*~~~~~~~~~+~~~~~~~~~*/
    /*~ SETUP DE BOTÕES ~*/
    /*~~~~~~~~~+~~~~~~~~~*/
    
    
  
    private void jbCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarActionPerformed
        cea = 'C';
        jlConcluido.setVisible(false);
        switch (pes) {
            case 'P':
                // CRIAR PRODUTOS
                // desativar: jr setor, estampa
                jrSetorMenu.setEnabled(false);
                jrEstampaMenu.setEnabled(false);
                // desativar: seções 1, 2 e 3
                ativSecao1(false);
                ativSecao2(false);
                ativSecao3(false);
                // ativar: seção 4
                ativSecao4(true);
                jlErroSelecionar.setVisible(false);
                break;
            case 'E':
                //CRIAR ESTAMPA
                // desativar: seção 1, 3 e 4
                ativSecao1(false);
                ativSecao3(false);
                ativSecao4(false);
                // ativar: seção 2
                ativSecao2(true);
                jlErroSelecionar.setVisible(false);
                break;
            case 'S':
                // CRIAR SETOR
                // desativar: seção 1, 3 e 4
                ativSecao1(false);
                ativSecao3(false);
                ativSecao4(false);
                // ativar: seção 2 (-nome estampa)
                ativSecao2(true);
                jlNomeEstampa.setEnabled(false);
                txtNomeEstampa.setEnabled(false);
                jlErroSelecionar.setVisible(false);
                break;
            default:
                jlErroSelecionar.setVisible(true);
                break;
        }
                
                
    }//GEN-LAST:event_jbCriarActionPerformed

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
        cea = 'A';
        jlConcluido.setVisible(false);
        if(pes == 'P' || pes == 'E' || pes == 'S'){
            ativSecao1(true);
            ativSecao2(false);
            ativSecao3(false);
            ativSecao4(false);
            jlErroSelecionar.setVisible(false);
        } 
        else {
            jlErroSelecionar.setVisible(true);
        }
    }//GEN-LAST:event_jbApagarActionPerformed

    private void txtCorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtCorAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCorAncestorAdded

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtNome1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNome1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1AncestorAdded

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void jrqtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrqtdeActionPerformed
        prodQPC = 'Q';
        // vai mostrar apenas a nova qnt
        jlNewQnte.setEnabled(true);
        txtQnte.setEnabled(true);
        jrPreco.setEnabled(false);
        jrCor.setEnabled(false);
        
        
    }//GEN-LAST:event_jrqtdeActionPerformed

    private void jrPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPrecoActionPerformed
        prodQPC = 'P';
        //jLabel e txt        
        jlValor.setEnabled(true);
        txtValor.setEnabled(true);
        
        jlNovaCor.setEnabled(false);
        txtCor.setEnabled(false);
        
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
        
        //jRadios
        jrqtde.setEnabled(false);
        jrCor.setEnabled(false);
       
    }//GEN-LAST:event_jrPrecoActionPerformed

    private void jrCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCorActionPerformed
        prodQPC = 'C';
        jlNovaCor.setEnabled(true);
        txtCor.setEnabled(true);
        
        jlValor.setEnabled(false);
        txtValor.setEnabled(false);
        
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
        
        jrqtde.setEnabled(false);
        jrPreco.setEnabled(false);
               
        
    }//GEN-LAST:event_jrCorActionPerformed

    private void jbConfirmaProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmaProxActionPerformed
        criarProduto();
    }//GEN-LAST:event_jbConfirmaProxActionPerformed

    private void txtNomeEstampaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNomeEstampaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEstampaAncestorAdded

    private void txtNomeEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEstampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEstampaActionPerformed

    private void txtQuantidadeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtQuantidadeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeAncestorAdded

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtEstampaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtEstampaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstampaAncestorAdded

    private void txtEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstampaActionPerformed

    private void txtprecoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtprecoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoAncestorAdded

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoActionPerformed

    private void txtSetorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtSetorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorAncestorAdded

    private void txtSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorActionPerformed

    private void txtCorzinhaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtCorzinhaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorzinhaAncestorAdded

    private void txtCorzinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorzinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorzinhaActionPerformed

    private void jbConfirmarSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarSetActionPerformed
        if(pes == 'S' && cea == 'A'){
            apagarSetor();
        }
        else if (pes == 'E' && cea == 'A'){
            apagarEstampa();
        }
        else if (pes == 'P' && cea == 'A'){
            apagarProduto();
        }
        
    }//GEN-LAST:event_jbConfirmarSetActionPerformed

    private void txtNominhoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNominhoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominhoAncestorAdded

    private void txtNominhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNominhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominhoActionPerformed

    private void jrEstampaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEstampaMenuActionPerformed
        // Jr - Estampa
        pes = 'E';
        jrSetorMenu.setEnabled(false);
        jrProdutoMenuzinho.setEnabled(false);
        jlConcluido.setVisible(false);
    }//GEN-LAST:event_jrEstampaMenuActionPerformed

    private void txtValorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtValorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorAncestorAdded

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtQnteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtQnteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQnteAncestorAdded

    private void txtQnteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQnteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQnteActionPerformed

    private void jbMenuCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuCriarActionPerformed
        // TODO add your handling code here:
         this.dispose();
        
        JanelaMenu telaMenu = new JanelaMenu();
        telaMenu.setVisible(true);
        telaMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbMenuCriarActionPerformed

    private void jrSetorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSetorMenuActionPerformed
        // Jradio - Setor
        pes = 'S';
        jrEstampaMenu.setEnabled(false);
        jrProdutoMenuzinho.setEnabled(false);
        jlConcluido.setVisible(false);
    }//GEN-LAST:event_jrSetorMenuActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
        pes = '-';
        /*
        jrProdutoMenuzinho.setEnabled(true);
        jrSetorMenu.setEnabled(true);
        jrEstampaMenu.setEnabled(true);
        
        jbEditar1.setEnabled(true);
        jbConfirmarSet.setEnabled(true);
        jlProdutinhoEscolher.setEnabled(true);
        
        ativSecao1(false);
        ativSecao2(false);
        ativSecao3(false);
        ativSecao4(false);*/
                
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbLimpandoBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpandoBotton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimpandoBotton1ActionPerformed

    private void jbConfirmarSetorzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarSetorzinhoActionPerformed
        if(pes == 'P' && cea == 'E' && prodQPC == 'Q'){
            editarProdQtde();
        } 
        else if(pes == 'P' && cea == 'E' && prodQPC == 'P'){
            editarProdPreco();
        }
        else if(pes == 'P' && cea == 'E' && prodQPC == 'C'){
            editarProdCor();
        }
        
        
    }//GEN-LAST:event_jbConfirmarSetorzinhoActionPerformed

    private void jbLimparEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparEditActionPerformed
        // TODO add your handling code here:
        txtNominho.setText("");
        
    }//GEN-LAST:event_jbLimparEditActionPerformed

    private void jbEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditar1ActionPerformed
        cea = 'E';
        jlConcluido.setVisible(false);
        switch (pes) {
            case 'P':
                // PRA EDITAR PRODUTO
                // desativar: seções 2 e 4
                ativSecao2(false);
                ativSecao4(false);
                // ativar: ID
                jlD.setEnabled(true);
                txtNominho.setEnabled(true);
                // ... e metade da seção 3
                jlProdutinhoEscolher.setEnabled(true);
                jrqtde.setEnabled(true);
                jrPreco.setEnabled(true);
                jrCor.setEnabled(true);
                jbMenuVoltEditzinho.setEnabled(true);
                jbConfirmarSetorzinho.setEnabled(true);
                jbVoltandojr.setEnabled(true);
                jlErroSelecionar.setVisible(false);
                break;
            case 'E':
                // desativar seções 3 e 4
                ativSecao3(false);
                ativSecao4(false);
                // ativar ID + seção 2 (-nome setor)
                jlD.setEnabled(true);
                txtNominho.setEnabled(true);
                ativSecao2(true);
                jlNomeSetor.setEnabled(false);
                txtNomeSetor.setEnabled(false);
                
                jlErroSelecionar.setVisible(false);
                break;
            case 'S':
                // desativar: seções 3 e 4
                ativSecao3(false);
                ativSecao4(false);
                // ativar: ID + seção 2 (-nome estampa)
                jlD.setEnabled(true);
                txtNominho.setEnabled(true);
                ativSecao2(true);
                jlNomeEstampa.setEnabled(false);
                txtNomeEstampa.setEnabled(false);
                jlErroSelecionar.setVisible(false);
                break;
            default:
                jlErroSelecionar.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jbEditar1ActionPerformed

    private void jbLimparCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCriacaoActionPerformed
        // TODO add your handling code here:
        txtSetor.setText("");
        txtEstampa.setText("");
        txtpreco.setText("");
        txtCorzinha.setText("");
        txtQuantidade.setText("");
    }//GEN-LAST:event_jbLimparCriacaoActionPerformed

    private void jrProdutoMenuzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrProdutoMenuzinhoActionPerformed
        // Jradio -- Produto
        pes = 'P';
        jrEstampaMenu.setEnabled(false);
        jrSetorMenu.setEnabled(false);
        jlConcluido.setVisible(false);
        
    }//GEN-LAST:event_jrProdutoMenuzinhoActionPerformed

    private void jbMenuVoltEditzinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuVoltEditzinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMenuVoltEditzinhoActionPerformed

    private void jbVoltandojrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltandojrActionPerformed
        // TODO add your handling code here:
        
        
        //JRadio
        jrqtde.setEnabled(true);
        jrPreco.setEnabled(true);
        jrCor.setEnabled(true);
        
        // jLabel e txt
        jlNewQnte.setEnabled(false);
        txtQnte.setEnabled(false);
                
        jlValor.setEnabled(false);
        txtValor.setEnabled(false);
                
        jlNovaCor.setEnabled(false);
        txtCor.setEnabled(false);
                        
        
        txtQnte.setText("");
        txtValor.setText("");
        txtCor.setText("");
    }//GEN-LAST:event_jbVoltandojrActionPerformed

    private void jbLimparEstSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparEstSetActionPerformed
        // TODO add your handling code here:
        txtNomeEstampa.setText("");
    }//GEN-LAST:event_jbLimparEstSetActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void txtNomeSetorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNomeSetorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeSetorAncestorAdded

    private void txtNomeSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeSetorActionPerformed

    private void jbConfirmarEstSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarEstSetActionPerformed
        if (pes == 'S' && cea == 'C'){      // CRIAR SETOR
            criarSetor();
        }
        else if (pes == 'E' && cea == 'C'){  // CRIAR ESTAMPA
            criarEstampa();
        }
        else if (pes == 'S' && cea == 'E'){ // EDITAR SETOR
           editarSetor();
        }
        else if (pes == 'E' && cea == 'E') // EDITAR ESTAMPA
            editarEstampa();
    }//GEN-LAST:event_jbConfirmarEstSetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbConfirmaProx;
    private javax.swing.JButton jbConfirmarEstSet;
    private javax.swing.JButton jbConfirmarSet;
    private javax.swing.JButton jbConfirmarSetorzinho;
    private javax.swing.JButton jbCriar;
    private javax.swing.JButton jbEditar1;
    private javax.swing.JButton jbLimpandoBotton1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimparCriacao;
    private javax.swing.JButton jbLimparEdit;
    private javax.swing.JButton jbLimparEstSet;
    private javax.swing.JButton jbMenuCriar;
    private javax.swing.JButton jbMenuVoltEditzinho;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbVoltandojr;
    private javax.swing.JLabel jlConcluido;
    private javax.swing.JLabel jlCorzinha;
    private javax.swing.JLabel jlCriarProduto;
    private javax.swing.JLabel jlD;
    private javax.swing.JLabel jlErroCriarProd;
    private javax.swing.JLabel jlErroESExiste;
    private javax.swing.JLabel jlErroIdInvalido;
    private javax.swing.JLabel jlErroSelecionar;
    private javax.swing.JLabel jlErroValorInvalido;
    private javax.swing.JLabel jlEstampinha;
    private javax.swing.JLabel jlNewQnte;
    private javax.swing.JLabel jlNomeEstampa;
    private javax.swing.JLabel jlNomeSetor;
    private javax.swing.JLabel jlNovaCor;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlProdutinhoEscolher;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlSetorEstampa;
    private javax.swing.JLabel jlValor;
    private javax.swing.JRadioButton jrCor;
    private javax.swing.JRadioButton jrEstampaMenu;
    private javax.swing.JRadioButton jrPreco;
    private javax.swing.JRadioButton jrProdutoMenuzinho;
    private javax.swing.JRadioButton jrSetorMenu;
    private javax.swing.JRadioButton jrqtde;
    private javax.swing.JTextPane txtConsulta;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtCorzinha;
    private javax.swing.JTextField txtEstampa;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNomeEstampa;
    private javax.swing.JTextField txtNomeSetor;
    private javax.swing.JTextField txtNominho;
    private javax.swing.JTextField txtQnte;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSetor;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
